services:
  frontend:
    build:
      context: . # Root directory of the project
      dockerfile: Skillify-Frontend/Dockerfile # Path to the frontend Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: . # Root directory of the project
      dockerfile: Skillify-Backend/Flask/Dockerfile # Correct path to the backend Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
