OPENAI_API_KEY: "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"
SERPER_API_KEY: "cfb35f37d156e36a7ae514e2317067fd613e4f41"
