# Use Node.js image
FROM node:18 AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY Skillify-frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY Skillify-frontend .

# Build the app
RUN npm run build

# Expose the port Next.js will run on
EXPOSE 3000

# Command to start the Next.js application
CMD ["npm", "run", "start"]
